ServerEvents.recipes(event => {
    // Be3Al2(SiO3)6 + 2Na2(SiF6) + Na2CO3 -> 3Na2BeF4 + Al2O3 + 8SiO2 + CO2
    event.recipes.gtceu.electric_blast_furnace('emerald_sintering')
        .itemInputs('29x gtceu:emerald_dust')
        .itemInputs('18x tfinfinity:sodium_fluorosilicate_dust')
        .itemInputs('6x gtceu:soda_ash_dust')
        .itemOutputs('tfinfinity:emerald_sinter_cake')
        .outputFluids('1000x gtceu:carbon_dioxide')
        .blastFurnaceTemp(1700)
        .duration(400)
        .EUt(GTValues.VA[GTValues.HV])
    
    event.recipes.gtceu.chemical_bath('wash_emerald_sinter_cake')
        .itemInputs('tfinfinity:emerald_sinter_cake')
        .inputFluids('6000x minecraft:water')
        .outputFluids('3000x tfinfinity:sodium_tetrafluoroberyllate')
        .itemOutputs('9x tfinfinity:emerald_sludge_residue_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor('beryllium_hydroxide_precipitation')
        .inputFluids('1000x tfinfinity:sodium_tetrafluoroberyllate')
        .inputFluids('2000x tfinfinity:sodium_hydroxide_solution')
        .itemOutputs('5x tfinfinity:beryllium_hydroxide_dust')
        .outputFluids('4000x tfinfinity:sodium_fluoride')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.tfinfinity.roaster('beryllium_oxide_from_hydroxide')
        .itemInputs('5x tfinfinity:beryllium_hydroxide_dust')
        .itemOutputs('2x tfinfinity:beryllium_oxide_dust')
        .outputFluids('1000x gtceu:steam')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.electric_blast_furnace('beryllium_chloride')
        .itemInputs('2x tfinfinity:beryllium_oxide_dust')
        .itemInputs('gtceu:carbon_dust')
        .inputFluids('2000x gtceu:chlorine')
        .itemOutputs('3x tfinfinity:beryllium_chloride_dust')
        .outputFluids('gtceu:carbon_monoxide')
        .blastFurnaceTemp(1700)
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    // ELECTROLYSIS in Molten Salt for Berylluum Metal

    event.recipes.gtceu.chemical_reactor('ammonium_tetrafluoroberyllate_precipitation')
        .itemInputs('5x tfinfinity:beryllium_hydroxide_dust')
        .inputFluids('2000x tfinfinity:ammonium_bifluoride')
        .itemOutputs('15x tfinfinity:ammonium_tetrafluoroberyllate_dust')
        .outputFluids('2000x minecraft:water')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('beryllium_fluoride_via_calcination') // Better machine for this?
        .itemInputs('15x tfinfinity:ammonium_tetrafluoroberyllate_dust')
        .itemOutputs('3x tfinfinity:beryllium_fluoride_dust')
        .outputFluids('2000x tfinfinity:hydrogen_fluoride')
        .outputFluids('1000x gtceu:ammonia')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.electric_blast_furnace('beryllium_from_fluoride')
        .itemInputs('3x tfinfinity:beryllium_fluoride_dust')
        .itemInputs('1x gtceu:magnesium_dust')
        .itemOutputs('1x gtceu:beryllium_dust')
        .itemOutputs('3x tfinfinity:magnesium_fluoride_dust')
        .blastFurnaceTemp(1700)
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('emerald_sludge_residue_separation')
        .itemInputs('9x tfinfinity:emerald_sludge_residue_dust')
        .inputFluids('3000x gtceu:sulfuric_acid')
        .outputFluids('1000x tfinfinity:aluminium_sulfate')
        .itemOutputs('24x gtceu:silicon_dioxide_dust')
        // .outputFluids('3000x minecraft:water')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])

    event.recipes.gtceu.chemical_reactor('aluminium_sulfate_precipitation')
        .inputFluids('1000x tfinfinity:aluminium_sulfate')
        .inputFluids('6000x gtceu:ammonia')
        .itemOutputs('14x tfinfinity:aluminium_hydroxide_dust')
        .outputFluids('3000x tfinfinity:ammonium_sulfate')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LV])
})