# This is the early configuration file for GregTech CEu Modern.
# The following options can be enabled or disabled if there is a compatibility issue.
# Change the line with your option name and =true or =false to enable or disable a rule.
# For example:
#   client.bloom.safe_mode=true -> client.bloom.safe_mode=false
# Do not include the # or ->. You may reset to defaults by deleting this file.
#
# Available options:

# Whether to use a 'safe mode' for bloom rendering
# NOTE: may be slower than 'normal' logic, but is considerably more stable and less prone to compatibility issues with other mods.
# Requires restarting the client to take effect.
#  default: false
client.bloom.safe_mode=true

# Whether to use a 'safe mode' for layered block faces
# NOTE: uses the standard chunk render path, which may restore visual artifacts, but is considerably more stable and less prone to compatibility issues with other mods.
# Requires restarting the client to take effect.
#  default: false
client.face_layer.safe_mode=false
