const registerTFILithiumMaterials = (event) => {
    event.create('tfinfinity:beta_spodumene')
        .formattedDisplayName('β-spodumene')
        .dust()
        .components('2x lithium', '2x aluminium', '4x silicon', '12x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0xDECFA6)
        .secondaryColor(0x8A567E)

    event.create('tfinfinity:lithium_sulfate')
        .liquid()
        .components('2x lithium', '1x sulfur', '4x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0x86E3C3)
        .secondaryColor(0x2A7D60)

    event.create('tfinfinity:spodumene_sulfate_cake')
        .dust()
        .components('2x lithium', '1x sulfur', '2x hydrogen', '2x aluminium', '4x silicon', '16x oxygen')
        .formula('(Li2SO4)(HAlSi2O6)2')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0xD1B96E)
        .secondaryColor(0x7A2B56)

    event.create('tfinfinity:spodumene_sludge_residue')
        .dust()
        .components('1x hydrogen', '1x aluminium', '2x silicon', '6x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0xA1966C)
        .secondaryColor(0x4A442D)

    event.create('tfinfinity:lithium_carbonate')
        .dust()
        .components('2x lithium', '1x carbon', '3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0xEBF2F7)
        .secondaryColor(0x57697A)
    
    event.create('tfinfinity:sodium_metasilicate')
        .dust()
        .components('2x sodium', '1x silicon', '3x oxygen')
        .color(0xCBEAE6)
        .secondaryColor(0x88B7B1)

    event.create('tfinfinity:lepidolite_sulfate_cake')
        .dust()
        .components('2x lithium', '1x sulfur', '3x potassium', '2x fluorine', '1x aluminium', '4x silicon', '10x oxygen')
        .formula('(Li2SO4)(KAlSi2O6)(SiO2)2(KF)2')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .color(0xC2A3B8)
        .secondaryColor(0x6E5265)

    event.create('tfinfinity:potassium_fluoride')
        .liquid()
        .components('1x potassium', '1x fluorine')
        .colorAverage()

    event.create('tfinfinity:lepidolite_leach_liquor')
        .liquid()
        .components('1x tfinfinity:lithium_sulfate', '2x tfinfinity:potassium_fluoride')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .colorAverage()

    event.create('tfinfinity:defluorinated_lepidolite_leach_liquor')
        .liquid()
        .components('1x tfinfinity:lithium_sulfate', '2x potassium_hydroxide')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .colorAverage()

    event.create('tfinfinity:lepidolite_tailings')
        .liquid()
        .components('1x tfinfinity:sodium_sulfate', '2x potassium_hydroxide')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .colorAverage()

    event.create('tfinfinity:potassium_feldspar_slurry')
        .liquid()
        .components('1x potassium_sulfate', '1x tfinfinity:aluminium_sulfate')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
        .colorAverage()
}